### ISSUE TITLE
step definition should be directly in the folder that has the same name as the feature file.

### ISSUE THREAD

**Issue by ahmadrymera** [VagnerSilva/testcucumbr-generator#2]
Now when we generate the step definition, it will be created inside a new folder same with **featurePath**

cypress/integration/features/Google_Test/cypress/integration/features/Google_Test_steps_spec.js
![image](https://user-images.githubusercontent.com/80019156/120436811-99134b80-c3a9-11eb-850e-a399a75cb6fc.png)

it should be cypress/integration/features/Google_Test/Google_Test_steps_spec.js
![image](https://user-images.githubusercontent.com/80019156/120437084-eabbd600-c3a9-11eb-8246-d3fbe36a74b1.png)

Can you fix it?

Thank You

**Comment by VagnerSilva** [comment]
Sorry, but I was unable to produce this error.

![image](https://user-images.githubusercontent.com/11982064/120597727-cc8ebe00-c41b-11eb-8125-ae65ff9fe55b.png)

This is the testcucumbr.conf.js configuration that was used in the test

![image](https://user-images.githubusercontent.com/11982064/120598178-56d72200-c41c-11eb-87cc-1e9cf6867809.png)

**Comment by ahmadrymera** [comment]
https://www.loom.com/share/87cc60c1369f460a96983d55af065a81

Mine like this.

**Comment by VagnerSilva** [comment]
Thanks for the video
Fix in testcucumbr-generator@1.0.5 version

**Comment by ahmadrymera** [comment]
it fixed now, thank you so much!
