### ISSUE TITLE
Update your readme.md

### ISSUE THREAD

**Issue by ahmadrymera** [VagnerSilva/testcucumbr-generator#3]
Now your readme.md give the wrong configuration

![image](https://user-images.githubusercontent.com/80019156/120437377-33738f00-c3aa-11eb-827b-db11b66367b5.png)
it should be **testcucumbr.conf** without.js extension

![image](https://user-images.githubusercontent.com/80019156/120437436-425a4180-c3aa-11eb-86bf-64ca500bdc3f.png)

**Comment by VagnerSilva** [comment]
Sorry, but I didn't change this part in the README. I always used it with 'JS' extension.
But feel free to use without the extension.

**Comment by ahmadrymera** [comment]
I know why when I use testcucumbr.conf.js from your readme.md it does not work.
in your readme.md you write **crypress** it should be cypress
![image](https://user-images.githubusercontent.com/80019156/120600075-89ac0500-c472-11eb-8ea4-3f20766b9203.png)
