### ISSUE TITLE
 option to select generate async or sync code

### ISSUE THREAD

**Issue by ahmadrymera** [VagnerSilva/testcucumbr-generator#4]
Can you add an option to select generate async or sync code?
In cypress I usually using sync
![image](https://user-images.githubusercontent.com/80019156/120577012-e0ebae80-c44d-11eb-8ac8-ec83491703ed.png)
![image](https://user-images.githubusercontent.com/80019156/120577109-0b3d6c00-c44e-11eb-95f6-cd901f524513.png)

**Comment by VagnerSilva** [comment]
Included in version 1.0.6 the 'arrow' property
