### ISSUE TITLE
Can you add generator for "Before, And, After" step?

### ISSUE THREAD

**Issue by ahmadrymera** [VagnerSilva/testcucumbr-generator#5]
I have step "And I want to breakfree"
but after generate "And" changed to "Given"
![image](https://user-images.githubusercontent.com/80019156/120599298-87957680-c471-11eb-94c6-401b4b4a2172.png)
![image](https://user-images.githubusercontent.com/80019156/120599338-92500b80-c471-11eb-8bb0-488d6eb8c5ad.png)

**Comment by VagnerSilva** [comment]
Sorry. How the script is generated via the 'gherkin' and 'cucumber' dependencies. 'And' is replaced by 'Given' because the 'And' function doesn't exist in 'cucumber'
